= Huluvu424242s Virtuelle Heimat

:Author:    Thomas Schubert
:Email:     <huluvu424242@gmail.com>
:toc-title: Table of Adventures

include::Profil.adoc[]

include::lebenslauf/Lebenslauf.adoc[]

include::projekte/Projekte.adoc[]

= Hobbies
[quote, Edsger Wybe Dijkstra]
Solange es keine Rechner gab,
stellte die Programmierung kein Problem dar,
mit ein paar leistungsschwachen Rechnern,
wurde sie zu einem kleinen Problem
und nun, mit gigantischen Rechnern,
ist sie auch ein gigantisches Problem.

In meinem Leben habe ich mich bisher für viele Dinge interessiert. Leider mußte ich auch feststellen, dass diese viel
Zeit in Anspruch nehmen und man sich wohl oder übel einschränken muß. Durch diese Erkenntnis haben es das Ausschlachten
alter Fernseher, das Löten von Leiterplatten, der Chemiebaukasten, das Arbeiten im Fotolabor, das Sezieren von Pflanzen,
die Stunden am Mikroskop, das Astrofernrohr und die Modelleisenbahn leider nicht bis in die heutige Zeit geschafft. Dafür 
habe ich viele neue Dinge kennengelernt, die ich nun ausprobiere :)

// Funken
include::hobbies/funk/Funken.adoc[]

include::hobbies/funk/buchstabieralphabete.adoc[]
include::hobbies/funk/Fernschreiben.adoc[]

// Kochen 
include::hobbies/Kochen.adoc[]

// Lesen 
include::hobbies/Lesen.adoc[]

// Schreiben
include::hobbies/Schreiben.adoc[]

// Filme
include::hobbies/Filme.adoc[]

// Kontakt
include::Kontakt.adoc[]

