== Schreiben

Angefangen hatte alles mit ein paar Reimen für Geburtstagskarten. Dann versuchte ich mit ein paar Zeilen mein Glück beim weiblichen Geschlecht.
Als ich begriffen hatte, dass sich in der Form eigene Emotionen transportieren lassen hab ich diese Möglichkeit im Internet ausgelebt um Luft
ab zu lassen. Irgendwann entstand der Wunsch erfahrene Geschichte und erlebte Emotionen als Handlung nieder zu schreiben. Genau daran arbeite
ich aktuell. Allerdings nicht so zielgerichtet wie dies wünschenswert wäre sondern eher sporadisch, ganz spontan in großen Abständen, 
wenn mir danach ist.

Die ersten Versuche ein Buch zu schreiben sind kläglich gescheitert. Ich als einziger Leser, war nicht einmal gewillt den Text zur Korrektur zu lesen,
so langweilig kam er mir vor. Ein Freund bestätigte mich darin und meinte ich solle es mal mit Dialogen im Text versuchen :) Ich kam mir vor wie 
H. R. Kunze in einem Nebensatz ein schreibendes Kind besingt: "Seine Texte handeln vom Schreiben, von etwas Anderem handeln sie nicht." Natürlich hat
er Recht und so versuche ich es nun mit Dialogen und Kurzgeschichten. Vielleicht bekomme ich sie ja dann mal irgendwann zusammen verbunden zu einer großen Geschichte.
Meine Intuition sagt mir zwar, dass es dazu eines Planes bedarf aber da halte ich es mit dem Spruch einer netten Bekannten: "Planlos geht mein Plan los".

Also denn! Letzte Warnung es folgen eigene Texte :)

* link:hobbies/schreiben/neuland/inhalt.html[Neuland]
* link:hobbies/schreiben/zone7/inhalt.html[Zone 7]
 
